server:
  servlet:
    context-path: /api

spring:
  application:
    name: ${SERVICE_NAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_ID}
    password: ${DB_MYSQL_PASSWORD}
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/${DB_MYSQL_DATABASE}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 10

  data:

#    mongodb:
#      database: ${MONGODB_DATABASE}
#      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
      username: ${REDIS_CACHE_USERNAME}
      password: ${REDIS_CACHE_PASSWORD}
      ttl-minutes: 1440

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}
      sign-up-token-expiry: ${JWT_SIGN_UP_TOKEN_EXPIRY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-1
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

batch-redis:
  host: ${REDIS_BATCH_HOST}
  port: ${REDIS_BATCH_PORT}
  username: ${REDIS_BATCH_USERNAME}
  password: ${REDIS_BATCH_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    display-request-duration: true
    filter: true
    doc-expansion: none
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    persist-authorization: true

